[book]
authors = ["ScanMountGoat"]
language = "en"
multilingual = false
src = "src"
title = "Xenoblade Rendering Research"

[output.html]
git-repository-url = "https://github.com/ScanMountGoat/xenoblade-rendering-research"
